server:
  port: 80
spring:
  application:
    name: test
#  datasource:
#    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/mng?useSSL=true&serverTimezone=GMT%2B8
#    username: root
#    password: root
#mybatis:
#  check-config-location: true
#  config-location: classpath:mybatis/mybatis-config.xml
#  mapper-locations: classpath:mybatis/mapper/*Mapper.xml